-define(Job, ecron_local_jobs).
-define(GlobalJob, ecron_global_jobs).
-define(Ecron, ecron).

-define(MAX_TIMEOUT, 4294967). %% (16#ffffffff div 1000) 49.71 days.
-define(Success, [ecron, success]).
-define(Failure, [ecron, failure]).
-define(Activate, [ecron, activate]).
-define(Deactivate, [ecron, deactivate]).
-define(Delete, [ecron, delete]).
-define(GlobalUp, [ecron, global, up]).
-define(GlobalDown, [ecron, global, down]).