on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        otp: ['24.3', '25.3', '26.2']
        rebar3: ['3.20.0', '3.19.0']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 as test get-deps
      - run: epmd -daemon
      - run: rebar3 as test proper -c
      - run: rebar3 as test eunit -c
      - run: rebar3 as test ct -c
      - run: rebar3 as test cover
      - name: Generate code coverage report
        if: matrix.otp == '26.2' && matrix.rebar3 == '3.20.0'
        run: rebar3 as test covertool generate
      - name: Upload code coverage to Codecov
        if: matrix.otp == '26.2' && matrix.rebar3 == '3.20.0'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: _build/test/covertool/ecron.covertool.xml
          flags: erlang-${{ matrix.otp_version }},os-${{ matrix.os }}
          name: Erlang/OTP ${{ matrix.otp_version }} on ${{ matrix.os }}
          verbose: true # optional (default = false)
